logging:
  level:
    root: INFO
    com:
      markets:
        getcandleshistoricalbatch:
          infra.oanda.v20.candles: INFO

infra:
  oanda:
    v20:
      token: 268f23b4e0988b8a0cfd47adcfdb116e-864c5eadbe35454dc9e08d614336fb38
      accountId: 101-002-8710634-001
      isProduction: false
      candlestick:
        enabled: true
        outputPathTemplate: "F:\\candles\\%s-candles-%s.csv"
